name: flutter_study_app
description: It's study app for training ENT.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.21.1
  get: ^4.6.5
  cloud_firestore: ^3.4.7
  google_fonts: ^3.0.1
  firebase_storage: ^10.3.8
  cached_network_image: ^3.2.2
  flutter_zoom_drawer: ^3.0.3
  firebase_auth: ^3.8.0
  url_launcher: ^6.1.5
  google_sign_in: ^5.4.1
  logger: ^1.1.0
  flutter_svg: ^1.1.5
  shimmer: ^2.0.0
  easy_separator: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/DB/papers/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/AppIcons.ttf
